# =========================================================
# File: 04_riskgroup_key_analyses.R
# Purpose:
#   Curated, submission-ready script for key downstream analyses between the
#   high-risk and low-risk groups in the TCGA-PRAD training cohort.
#
# What this script does:
#   1. Reads the TCGA risk file and TCGA expression matrix generated by
#      03_signature_model_core.R.
#   2. Performs GO and KEGG enrichment analysis for the final prognostic
#      signature genes.
#   3. Performs GSEA between the high-risk and low-risk groups.
#   4. Optionally performs immune-function ssGSEA if immune.gmt is available.
#   5. Compares TIDE scores between the high-risk and low-risk groups.
#   6. Compares immune subtype distributions between the high-risk and low-risk
#      groups.
#   7. Compares immune checkpoint-related gene expression between the two
#      groups.
#   8. Optionally performs transcriptome-based predicted drug-response analysis
#      using oncoPredict if GDSC2 training objects are available.
#
# Main required input files:
#   1. results/00_tables/risk.TCGA.txt   (or ./risk.TCGA.txt)
#   2. results/00_tables/tcga_dat_T.txt  (or ./tcga_dat_T.txt)
#   3. results/00_tables/best_model_genes.txt OR Signature.txt
#
# Optional input files:
#   4. c2.cp.kegg.Hs.symbols.gmt
#   5. immune.gmt
#   6. TIDE.csv
#   7. Subtype_Immune_Model_Based.txt
#   8. gene.txt
#   9. GDSC2_Expr.rds
#   10. GDSC2_Res.rds
#
# Main output files:
#   1. results/04_riskgroup_key_analyses/01_functional/GO_results.tsv
#   2. results/04_riskgroup_key_analyses/01_functional/KEGG_results.tsv
#   3. results/04_riskgroup_key_analyses/01_functional/GSEA_results.tsv
#   4. results/04_riskgroup_key_analyses/02_immune/immune_ssgsea_scores.tsv
#   5. results/04_riskgroup_key_analyses/02_immune/TIDE_results.tsv
#   6. results/04_riskgroup_key_analyses/02_immune/immuneSubtype_results.tsv
#   7. results/04_riskgroup_key_analyses/02_immune/checkpoint_results.tsv
#   8. results/04_riskgroup_key_analyses/03_drug/drugSensitivity_results.tsv
#
# Notes:
#   - Only manuscript-relevant downstream analyses are retained here.
#   - Exploratory infiltration-correlation and ESTIMATE/TME-score modules from
#     the original scripts are intentionally excluded from the public version.
#   - The primary downstream inputs are risk.TCGA.txt and tcga_dat_T.txt from
#     03_signature_model_core.R.
# =========================================================

options(stringsAsFactors = FALSE, check.names = FALSE, warn = 1)
set.seed(1234)

CFG <- list(
  RESULTS_DIR = file.path(getwd(), "results", "04_riskgroup_key_analyses"),
  PDF_WIDTH = 7,
  PDF_HEIGHT = 6,
  TIFF_DPI = 600,
  RISK_COL = c("Low" = "#2F7FC1FF", "High" = "#D94738FF"),
  P_CUTOFF = 0.05,
  DRUG_P_CUTOFF = 0.05,
  TOP_CHECKPOINT_PLOT = 20,
  TOP_GSEA_PLOT = 10,
  DRUGS_OF_INTEREST = c(
    "bicalutamide", "cisplatin", "docetaxel", "doxorubicin", "etoposide",
    "gemcitabine", "methotrexate", "mitomycin c", "paclitaxel", "vinblastine"
  )
)

DIRS <- list(
  functional = file.path(CFG$RESULTS_DIR, "01_functional"),
  immune = file.path(CFG$RESULTS_DIR, "02_immune"),
  drug = file.path(CFG$RESULTS_DIR, "03_drug"),
  logs = file.path(CFG$RESULTS_DIR, "99_logs")
)
invisible(lapply(DIRS, dir.create, recursive = TRUE, showWarnings = FALSE))

msg <- function(...) {
  cat(sprintf("[%s] ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")), ..., "\n", sep = "")
}

find_first_existing <- function(paths) {
  hit <- paths[file.exists(paths)]
  if (length(hit) == 0) return(NA_character_)
  hit[1]
}

check_and_load_packages <- function(pkgs) {
  missing_pkgs <- pkgs[!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]
  if (length(missing_pkgs) > 0) {
    stop(
      "Missing required packages: ",
      paste(missing_pkgs, collapse = ", "),
      "\nPlease install them before running this script."
    )
  }
  invisible(lapply(pkgs, function(x) suppressPackageStartupMessages(library(x, character.only = TRUE))))
}

check_and_load_packages(c("data.table", "dplyr", "ggplot2", "ggpubr", "limma", "patchwork"))

save_gg_dual <- function(plot_obj, filename_stub, width = CFG$PDF_WIDTH, height = CFG$PDF_HEIGHT, dpi = CFG$TIFF_DPI) {
  ggplot2::ggsave(paste0(filename_stub, ".pdf"), plot = plot_obj, width = width, height = height,
                  units = "in", device = grDevices::cairo_pdf)
  ggplot2::ggsave(paste0(filename_stub, ".png"), plot = plot_obj, width = width, height = height,
                  units = "in", dpi = dpi)
}

save_base_dual <- function(plot_fun, filename_stub, width = CFG$PDF_WIDTH, height = CFG$PDF_HEIGHT, dpi = CFG$TIFF_DPI) {
  grDevices::pdf(paste0(filename_stub, ".pdf"), width = width, height = height, family = "Helvetica")
  plot_fun()
  grDevices::dev.off()
  grDevices::png(paste0(filename_stub, ".png"), width = width, height = height, units = "in", res = dpi)
  plot_fun()
  grDevices::dev.off()
}

standardize_tcga_id <- function(x) {
  x <- as.character(x)
  x <- gsub("\\.", "-", x)
  ifelse(grepl("^TCGA-", x), substr(x, 1, 12), x)
}

average_duplicate_rows <- function(mat) {
  mat <- as.matrix(mat)
  storage.mode(mat) <- "numeric"
  rn <- rownames(mat)
  if (is.null(rn)) stop("Matrix must have rownames.")
  if (!anyDuplicated(rn)) return(mat)
  uniq <- unique(rn)
  out <- t(vapply(uniq, function(g) {
    idx <- which(rn == g)
    if (length(idx) == 1) {
      as.numeric(mat[idx, ])
    } else {
      colMeans(mat[idx, , drop = FALSE], na.rm = TRUE)
    }
  }, numeric(ncol(mat))))
  rownames(out) <- uniq
  colnames(out) <- colnames(mat)
  out
}

prepare_tcga_expression <- function(expr_file) {
  rt <- data.table::fread(expr_file, data.table = FALSE, check.names = FALSE)
  if (ncol(rt) < 2) stop("Expression file must contain gene column and sample columns: ", expr_file)
  gene_col <- colnames(rt)[1]
  genes <- rt[[gene_col]]
  expr <- as.matrix(rt[, -1, drop = FALSE])
  rownames(expr) <- genes
  storage.mode(expr) <- "numeric"
  expr <- average_duplicate_rows(expr)
  expr <- expr[rowMeans(expr, na.rm = TRUE) > 0, , drop = FALSE]

  sample_type <- sapply(strsplit(colnames(expr), "-"), function(z) if (length(z) >= 4) substr(z[4], 1, 1) else NA_character_)
  tumor_keep <- !is.na(sample_type) & sample_type == "0"
  if (sum(tumor_keep) == 0) {
    msg("No explicit TCGA tumor barcodes detected in expression matrix; using all columns as provided.")
  } else {
    expr <- expr[, tumor_keep, drop = FALSE]
  }

  std_ids <- standardize_tcga_id(colnames(expr))
  if (anyDuplicated(std_ids)) {
    tmp <- t(expr)
    rownames(tmp) <- std_ids
    tmp <- average_duplicate_rows(tmp)
    expr <- t(tmp)
  } else {
    colnames(expr) <- std_ids
  }
  expr
}

prepare_risk_file <- function(risk_file) {
  risk <- data.table::fread(risk_file, data.table = FALSE, check.names = FALSE)
  if (!("ID" %in% colnames(risk))) colnames(risk)[1] <- "ID"
  risk$ID <- standardize_tcga_id(risk$ID)
  risk <- risk[!duplicated(risk$ID), , drop = FALSE]
  rownames(risk) <- risk$ID

  if (!("Risk" %in% colnames(risk))) {
    stop("risk.TCGA.txt must contain a 'Risk' column with Low/High labels.")
  }
  risk$Risk <- factor(as.character(risk$Risk), levels = c("Low", "High"))
  risk
}

get_best_model_genes <- function() {
  best_file <- find_first_existing(c(
    file.path("results", "00_tables", "best_model_genes.txt"),
    "best_model_genes.txt"
  ))
  sig_file <- find_first_existing(c("Signature.txt", file.path("results", "00_tables", "Signature.txt")))

  genes <- character(0)
  if (!is.na(best_file)) {
    x <- data.table::fread(best_file, data.table = FALSE, check.names = FALSE)
    genes <- unique(as.character(x[[1]]))
  }
  if (length(genes) == 0 && !is.na(sig_file)) {
    x <- data.table::fread(sig_file, data.table = FALSE, check.names = FALSE)
    cand_cols <- c("gene", "Gene", "gene_symbol", "symbol")
    hit <- cand_cols[cand_cols %in% colnames(x)]
    if (length(hit) > 0) {
      genes <- unique(as.character(x[[hit[1]]]))
    } else {
      genes <- unique(as.character(x[[1]]))
    }
  }
  genes <- genes[!is.na(genes) & nzchar(genes)]
  if (length(genes) == 0) stop("Could not identify best-model genes from best_model_genes.txt or Signature.txt")
  genes
}

checkpoint_genes_default <- c(
  "IDO1","LAG3","CTLA4","TNFRSF9","ICOS","CD80","PDCD1LG2","TIGIT","CD70","TNFSF9",
  "ICOSLG","KIR3DL1","CD86","PDCD1","LAIR1","TNFRSF8","TNFSF15","TNFRSF14","IDO2","CD276",
  "CD40","TNFRSF4","TNFSF14","HHLA2","CD244","CD274","HAVCR2","CD27","BTLA","LGALS9",
  "TMIGD2","CD28","CD48","TNFRSF25","CD40LG","ADORA2A","VTCN1","CD160","CD44","TNFSF18",
  "TNFRSF18","BTNL2","C10orf54","CD200R1","TNFSF4","CD200","NRP1"
)

read_checkpoint_gene_list <- function() {
  gene_file <- find_first_existing(c("gene.txt", file.path("results", "gene.txt")))
  if (is.na(gene_file)) return(checkpoint_genes_default)
  x <- data.table::fread(gene_file, data.table = FALSE, header = FALSE, check.names = FALSE)
  unique(as.character(x[[1]]))
}

# -----------------------------
# Input file resolution
# -----------------------------
risk_file <- find_first_existing(c(
  file.path("results", "00_tables", "risk.TCGA.txt"),
  "risk.TCGA.txt"
))
expr_file <- find_first_existing(c(
  file.path("results", "00_tables", "tcga_dat_T.txt"),
  "tcga_dat_T.txt"
))
kegg_gmt_file <- find_first_existing(c("c2.cp.kegg.Hs.symbols.gmt", file.path("gmt", "c2.cp.kegg.Hs.symbols.gmt")))
immune_gmt_file <- find_first_existing(c("immune.gmt", file.path("gmt", "immune.gmt")))
tide_file <- find_first_existing(c("TIDE.csv", file.path("results", "TIDE.csv")))
subtype_file <- find_first_existing(c("Subtype_Immune_Model_Based.txt", file.path("results", "Subtype_Immune_Model_Based.txt")))
gdsc_expr_file <- find_first_existing(c("GDSC2_Expr.rds", file.path("results", "GDSC2_Expr.rds")))
gdsc_res_file <- find_first_existing(c("GDSC2_Res.rds", file.path("results", "GDSC2_Res.rds")))

if (is.na(risk_file)) stop("Could not find risk.TCGA.txt")
if (is.na(expr_file)) stop("Could not find tcga_dat_T.txt")

msg("Using risk file: ", risk_file)
msg("Using expression file: ", expr_file)

risk <- prepare_risk_file(risk_file)
expr_mat <- prepare_tcga_expression(expr_file)
common_samples <- intersect(colnames(expr_mat), rownames(risk))
if (length(common_samples) == 0) stop("No overlapping samples between risk file and expression matrix.")
expr_mat <- expr_mat[, common_samples, drop = FALSE]
risk <- risk[common_samples, , drop = FALSE]

write.table(
  data.frame(ID = common_samples, Risk = risk$Risk, stringsAsFactors = FALSE),
  file = file.path(DIRS$logs, "common_samples.tsv"),
  sep = "\t", quote = FALSE, row.names = FALSE
)

# -----------------------------
# 1. GO / KEGG enrichment
# -----------------------------
msg("Running GO/KEGG enrichment analysis")
check_and_load_packages(c("clusterProfiler", "org.Hs.eg.db", "enrichplot"))

best_model_genes <- get_best_model_genes()
best_model_genes <- unique(best_model_genes[best_model_genes %in% rownames(expr_mat)])
if (length(best_model_genes) == 0) {
  msg("Warning: no best-model genes overlap with expression matrix; GO/KEGG will use the original gene list without overlap filtering.")
  best_model_genes <- get_best_model_genes()
}

write.table(
  data.frame(gene = best_model_genes, stringsAsFactors = FALSE),
  file = file.path(DIRS$functional, "best_model_genes_input.tsv"),
  sep = "\t", quote = FALSE, row.names = FALSE
)

gene_map <- clusterProfiler::bitr(
  best_model_genes,
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Hs.eg.db::org.Hs.eg.db
)
gene_map <- unique(gene_map[!is.na(gene_map$ENTREZID), , drop = FALSE])
write.table(gene_map, file = file.path(DIRS$functional, "best_model_genes_symbol2entrez.tsv"),
            sep = "\t", quote = FALSE, row.names = FALSE)

if (nrow(gene_map) > 0) {
  ego <- clusterProfiler::enrichGO(
    gene = unique(gene_map$ENTREZID),
    OrgDb = org.Hs.eg.db::org.Hs.eg.db,
    keyType = "ENTREZID",
    ont = "ALL",
    pvalueCutoff = 1,
    qvalueCutoff = 1,
    readable = TRUE
  )
  ego_df <- as.data.frame(ego)
  write.table(ego_df, file = file.path(DIRS$functional, "GO_results.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)
  if (nrow(ego_df) > 0) {
    p_go <- enrichplot::dotplot(ego, showCategory = min(15, nrow(ego_df)), split = "ONTOLOGY") +
      ggplot2::facet_grid(ONTOLOGY ~ ., scales = "free")
    save_gg_dual(p_go, file.path(DIRS$functional, "GO_dotplot"), width = 10, height = 7)
  }

  ekegg <- clusterProfiler::enrichKEGG(
    gene = unique(gene_map$ENTREZID),
    organism = "hsa",
    pvalueCutoff = 1,
    qvalueCutoff = 1
  )
  ekegg_df <- as.data.frame(ekegg)
  write.table(ekegg_df, file = file.path(DIRS$functional, "KEGG_results.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)
  if (nrow(ekegg_df) > 0) {
    p_kegg <- enrichplot::dotplot(ekegg, showCategory = min(20, nrow(ekegg_df)))
    save_gg_dual(p_kegg, file.path(DIRS$functional, "KEGG_dotplot"), width = 9, height = 7)
  }
} else {
  msg("Skipping GO/KEGG because no ENTREZID mapping was obtained.")
}

# -----------------------------
# 2. GSEA high vs low risk
# -----------------------------
if (!is.na(kegg_gmt_file)) {
  msg("Running GSEA: ", kegg_gmt_file)
  check_and_load_packages(c("clusterProfiler", "GSEABase"))

  design <- stats::model.matrix(~ 0 + risk$Risk)
  colnames(design) <- levels(risk$Risk)
  fit <- limma::lmFit(expr_mat, design)
  contrast <- limma::makeContrasts(High - Low, levels = design)
  fit2 <- limma::contrasts.fit(fit, contrast)
  fit2 <- limma::eBayes(fit2)
  de_tab <- limma::topTable(fit2, number = Inf, sort.by = "none")
  de_tab$gene <- rownames(de_tab)
  write.table(de_tab, file = file.path(DIRS$functional, "high_vs_low_limma.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)

  geneList <- de_tab$logFC
  names(geneList) <- de_tab$gene
  geneList <- sort(geneList, decreasing = TRUE)

  pathways <- GSEABase::getGmt(kegg_gmt_file)
  pathways_list <- lapply(pathways, GSEABase::geneIds)
  names(pathways_list) <- vapply(pathways, GSEABase::setName, character(1))

  gsea_res <- tryCatch(
    clusterProfiler::GSEA(
      geneList = geneList,
      TERM2GENE = stack(pathways_list)[, c("ind", "values")],
      pvalueCutoff = 1,
      verbose = FALSE,
      seed = TRUE
    ),
    error = function(e) {
      msg("GSEA failed: ", conditionMessage(e))
      NULL
    }
  )

  if (!is.null(gsea_res)) {
    gsea_df <- as.data.frame(gsea_res)
    write.table(gsea_df, file = file.path(DIRS$functional, "GSEA_results.tsv"),
                sep = "\t", quote = FALSE, row.names = FALSE)
    if (nrow(gsea_df) > 0) {
      sel_n <- min(CFG$TOP_GSEA_PLOT, nrow(gsea_df))
      p_gsea <- enrichplot::dotplot(gsea_res, showCategory = sel_n, split = ".sign")
      save_gg_dual(p_gsea, file.path(DIRS$functional, "GSEA_dotplot"), width = 10, height = 7)
    }
  }
} else {
  msg("Skipping GSEA because c2.cp.kegg.Hs.symbols.gmt was not found.")
}

# -----------------------------
# 3. Optional immune-function ssGSEA
# -----------------------------
if (!is.na(immune_gmt_file)) {
  msg("Running immune-function ssGSEA: ", immune_gmt_file)
  check_and_load_packages(c("GSVA", "GSEABase", "reshape2"))

  geneSet <- GSEABase::getGmt(immune_gmt_file, geneIdType = GSEABase::SymbolIdentifier())
  if ("ssgseaParam" %in% getNamespaceExports("GSVA")) {
    param <- GSVA::ssgseaParam(exprData = expr_mat, geneSets = geneSet)
    ssgseaScore <- GSVA::gsva(param, verbose = FALSE)
  } else {
    ssgseaScore <- GSVA::gsva(expr = expr_mat, gset.idx.list = lapply(geneSet, GSEABase::geneIds),
                              method = "ssgsea", kcdf = "Gaussian", verbose = FALSE)
  }

  ssgsea_df <- data.frame(Feature = rownames(ssgseaScore), ssgseaScore, check.names = FALSE)
  write.table(ssgsea_df, file = file.path(DIRS$immune, "immune_ssgsea_scores.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)

  score_long <- reshape2::melt(t(ssgseaScore))
  colnames(score_long) <- c("ID", "Feature", "Score")
  score_long$Risk <- risk[score_long$ID, "Risk"]
  score_long <- score_long[stats::complete.cases(score_long), , drop = FALSE]

  p_imm <- ggpubr::ggboxplot(score_long, x = "Feature", y = "Score", fill = "Risk",
                             palette = CFG$RISK_COL, outlier.shape = NA, add = "none") +
    ggpubr::stat_compare_means(aes(group = Risk), method = "wilcox.test", label = "p.signif") +
    ggplot2::theme_bw(base_size = 11) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 50, hjust = 1))
  save_gg_dual(p_imm, file.path(DIRS$immune, "immune_ssgsea_boxplot"), width = 10, height = 6)
}

# -----------------------------
# 4. TIDE comparison
# -----------------------------
if (!is.na(tide_file)) {
  msg("Running TIDE comparison: ", tide_file)
  tide <- data.table::fread(tide_file, data.table = FALSE, check.names = FALSE)
  if (ncol(tide) < 2) {
    msg("Skipping TIDE because the file does not contain the expected columns.")
  } else {
    if (!("TIDE" %in% colnames(tide))) {
      tide_col <- colnames(tide)[ncol(tide)]
    } else {
      tide_col <- "TIDE"
    }
    sample_col <- colnames(tide)[1]
    tide$ID <- standardize_tcga_id(tide[[sample_col]])
    tide[[tide_col]] <- suppressWarnings(as.numeric(tide[[tide_col]]))
    tide <- stats::aggregate(tide[[tide_col]], by = list(ID = tide$ID), FUN = mean, na.rm = TRUE)
    colnames(tide)[2] <- "TIDE"
    rownames(tide) <- tide$ID
    tide <- tide[intersect(rownames(tide), rownames(risk)), , drop = FALSE]
    tide$Risk <- risk[rownames(tide), "Risk"]
    write.table(data.frame(ID = rownames(tide), tide, check.names = FALSE),
                file = file.path(DIRS$immune, "TIDE_results.tsv"),
                sep = "\t", quote = FALSE, row.names = FALSE)

    p_tide <- ggpubr::ggviolin(
      data = tide,
      x = "Risk", y = "TIDE", fill = "Risk", palette = CFG$RISK_COL,
      add = "boxplot", add.params = list(fill = "white", width = 0.25)
    ) +
      ggpubr::stat_compare_means(comparisons = list(c("Low", "High")), method = "t.test", label = "p.signif") +
      ggplot2::theme_bw(base_size = 12)
    save_gg_dual(p_tide, file.path(DIRS$immune, "TIDE_violin"), width = 6, height = 5)
  }
} else {
  msg("Skipping TIDE because TIDE.csv was not found.")
}

# -----------------------------
# 5. Immune subtype comparison
# -----------------------------
subtype_df <- NULL
if (!is.na(subtype_file)) {
  msg("Running immune subtype comparison using file: ", subtype_file)
  subtype_df <- data.table::fread(subtype_file, data.table = FALSE, check.names = FALSE)
  rownames(subtype_df) <- standardize_tcga_id(rownames(subtype_df))
} else if (requireNamespace("TCGAbiolinks", quietly = TRUE)) {
  msg("Subtype_Immune_Model_Based.txt not found; trying TCGAbiolinks::PanCancerAtlas_subtypes().")
  subtype_try <- tryCatch(TCGAbiolinks::PanCancerAtlas_subtypes(), error = function(e) NULL)
  if (!is.null(subtype_try)) subtype_df <- subtype_try
}

if (!is.null(subtype_df)) {
  cn <- colnames(subtype_df)
  id_col <- c("sample", "Sample", "barcode", "patient", "submitter_id")
  id_hit <- id_col[id_col %in% cn]
  if (length(id_hit) > 0) {
    subtype_df$ID <- standardize_tcga_id(subtype_df[[id_hit[1]]])
  } else if (nrow(subtype_df) > 0 && !is.null(rownames(subtype_df))) {
    subtype_df$ID <- standardize_tcga_id(rownames(subtype_df))
  }

  subtype_col_cands <- c("Subtype_mRNA", "subtype", "Subtype", "Immune_Subtype", "immuneSubtype")
  subtype_hit <- subtype_col_cands[subtype_col_cands %in% colnames(subtype_df)]
  if (length(subtype_hit) == 0) subtype_hit <- colnames(subtype_df)[1]
  subtype_col <- subtype_hit[1]

  keep <- !is.na(subtype_df$ID) & subtype_df$ID %in% rownames(risk)
  subtype_use <- data.frame(
    ID = subtype_df$ID[keep],
    subtype = as.character(subtype_df[[subtype_col]][keep]),
    stringsAsFactors = FALSE
  )
  subtype_use$subtype <- gsub(".+Immune |\\)", "", subtype_use$subtype)
  subtype_use <- subtype_use[!duplicated(subtype_use$ID), , drop = FALSE]
  subtype_use$Risk <- risk[subtype_use$ID, "Risk"]

  tab <- table(subtype_use$subtype, subtype_use$Risk)
  chisq_p <- tryCatch(stats::chisq.test(tab)$p.value, error = function(e) NA_real_)

  out_sub <- as.data.frame(tab)
  colnames(out_sub) <- c("Subtype", "Risk", "Count")
  out_sub$chi_square_p <- chisq_p
  write.table(out_sub, file = file.path(DIRS$immune, "immuneSubtype_results.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)

  p_sub <- ggplot2::ggplot(out_sub, ggplot2::aes(x = Subtype, y = Count, fill = Risk)) +
    ggplot2::geom_col(position = "fill") +
    ggplot2::scale_fill_manual(values = CFG$RISK_COL) +
    ggplot2::labs(y = "Proportion", subtitle = paste0("Chi-square P = ", signif(chisq_p, 3))) +
    ggplot2::theme_bw(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
  save_gg_dual(p_sub, file.path(DIRS$immune, "immuneSubtype_stacked"), width = 7, height = 5)
} else {
  msg("Skipping immune subtype comparison because subtype annotation was not available.")
}

# -----------------------------
# 6. Immune checkpoint comparison
# -----------------------------
msg("Running immune checkpoint comparison")
checkpoint_genes <- read_checkpoint_gene_list()
checkpoint_genes <- intersect(checkpoint_genes, rownames(expr_mat))
if (length(checkpoint_genes) == 0) {
  msg("Skipping checkpoint comparison because no checkpoint genes overlap with expression matrix.")
} else {
  cp_expr <- t(expr_mat[checkpoint_genes, , drop = FALSE])
  cp_expr <- log2(cp_expr + 1)
  cp_df <- data.frame(ID = rownames(cp_expr), cp_expr, check.names = FALSE)
  cp_df$Risk <- risk[cp_df$ID, "Risk"]

  stats_list <- lapply(checkpoint_genes, function(g) {
    dat <- data.frame(expr = cp_df[[g]], Risk = cp_df$Risk)
    dat <- dat[stats::complete.cases(dat), , drop = FALSE]
    if (nrow(dat) < 6 || length(unique(dat$Risk)) < 2 || stats::sd(dat$expr) < 1e-6) {
      return(data.frame(Gene = g, P_value = NA_real_, Median_Low = NA_real_, Median_High = NA_real_, Log2FC_High_vs_Low = NA_real_))
    }
    wt <- stats::wilcox.test(expr ~ Risk, data = dat)
    med_low <- stats::median(dat$expr[dat$Risk == "Low"], na.rm = TRUE)
    med_high <- stats::median(dat$expr[dat$Risk == "High"], na.rm = TRUE)
    data.frame(
      Gene = g,
      P_value = wt$p.value,
      Median_Low = med_low,
      Median_High = med_high,
      Log2FC_High_vs_Low = med_high - med_low,
      stringsAsFactors = FALSE
    )
  })
  checkpoint_stats <- dplyr::bind_rows(stats_list)
  checkpoint_stats$adj_P <- stats::p.adjust(checkpoint_stats$P_value, method = "BH")
  checkpoint_stats <- checkpoint_stats[order(checkpoint_stats$P_value), , drop = FALSE]
  write.table(checkpoint_stats, file = file.path(DIRS$immune, "checkpoint_results.tsv"),
              sep = "\t", quote = FALSE, row.names = FALSE)

  plot_genes <- head(checkpoint_stats$Gene[!is.na(checkpoint_stats$P_value)], CFG$TOP_CHECKPOINT_PLOT)
  if (length(plot_genes) > 0) {
    cp_long <- reshape2::melt(cp_df[, c(plot_genes, "Risk"), drop = FALSE], id.vars = "Risk")
    colnames(cp_long) <- c("Risk", "Gene", "Expression")
    cp_long$Risk <- factor(cp_long$Risk, levels = c("Low", "High"))
    p_cp <- ggpubr::ggboxplot(
      cp_long, x = "Gene", y = "Expression", fill = "Risk",
      palette = CFG$RISK_COL, outlier.shape = NA, width = 0.8
    ) +
      ggpubr::stat_compare_means(aes(group = Risk), method = "wilcox.test", label = "p.signif") +
      ggplot2::theme_bw(base_size = 11) +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 50, hjust = 1))
    save_gg_dual(p_cp, file.path(DIRS$immune, "checkpoint_boxplot_top"), width = 10, height = 5)
  }
}

# -----------------------------
# 7. Optional oncoPredict drug sensitivity
# -----------------------------
if (!is.na(gdsc_expr_file) && !is.na(gdsc_res_file) && requireNamespace("oncoPredict", quietly = TRUE)) {
  msg("Running predicted drug-response analysis")
  check_and_load_packages(c("oncoPredict", "tidyr"))

  GDSC2_Expr <- readRDS(gdsc_expr_file)
  GDSC2_Res <- readRDS(gdsc_res_file)
  GDSC2_Res <- exp(GDSC2_Res)

  old_wd <- getwd()
  on.exit(setwd(old_wd), add = TRUE)
  setwd(DIRS$drug)
  oncoPredict::calcPhenotype(
    trainingExprData = GDSC2_Expr,
    trainingPtype = GDSC2_Res,
    testExprData = expr_mat,
    batchCorrect = "eb",
    powerTransformPhenotype = TRUE,
    removeLowVaryingGenes = 0.2,
    minNumSamples = 10,
    printOutput = TRUE,
    removeLowVaringGenesFrom = "rawData"
  )
  setwd(old_wd)

  pred_file <- file.path(DIRS$drug, "DrugPredictions.csv")
  if (file.exists(pred_file)) {
    drug <- read.csv(pred_file, header = TRUE, check.names = FALSE, row.names = 1)
    rownames(drug) <- standardize_tcga_id(rownames(drug))
    drug <- drug[!duplicated(rownames(drug)), , drop = FALSE]
    colnames(drug) <- tolower(gsub("(.*)_(\\d+)$", "\\1", colnames(drug)))

    common_drug_samples <- intersect(rownames(drug), rownames(risk))
    drug <- drug[common_drug_samples, , drop = FALSE]
    risk_drug <- risk[common_drug_samples, , drop = FALSE]

    stats_drug <- lapply(colnames(drug), function(dr) {
      dat <- data.frame(Value = as.numeric(drug[, dr]), Risk = risk_drug$Risk)
      dat <- dat[stats::complete.cases(dat), , drop = FALSE]
      if (nrow(dat) < 6 || length(unique(dat$Risk)) < 2) {
        return(data.frame(Drug = dr, P_value = NA_real_, Median_Low = NA_real_, Median_High = NA_real_))
      }
      wt <- stats::wilcox.test(Value ~ Risk, data = dat)
      data.frame(
        Drug = dr,
        P_value = wt$p.value,
        Median_Low = stats::median(dat$Value[dat$Risk == "Low"], na.rm = TRUE),
        Median_High = stats::median(dat$Value[dat$Risk == "High"], na.rm = TRUE),
        stringsAsFactors = FALSE
      )
    })
    drug_stats <- dplyr::bind_rows(stats_drug)
    drug_stats$adj_P <- stats::p.adjust(drug_stats$P_value, method = "BH")
    drug_stats$SelectedInManuscript <- tolower(drug_stats$Drug) %in% CFG$DRUGS_OF_INTEREST
    drug_stats <- drug_stats[order(drug_stats$P_value), , drop = FALSE]
    write.table(drug_stats, file = file.path(DIRS$drug, "drugSensitivity_results.tsv"),
                sep = "\t", quote = FALSE, row.names = FALSE)

    top_drugs <- unique(c(
      drug_stats$Drug[drug_stats$SelectedInManuscript],
      head(drug_stats$Drug[!is.na(drug_stats$P_value)], 6)
    ))
    top_drugs <- top_drugs[top_drugs %in% colnames(drug)]
    if (length(top_drugs) > 0) {
      plot_df <- data.frame(ID = rownames(drug), drug[, top_drugs, drop = FALSE], check.names = FALSE)
      plot_df$Risk <- risk_drug[plot_df$ID, "Risk"]
      plot_long <- reshape2::melt(plot_df, id.vars = c("ID", "Risk"))
      colnames(plot_long) <- c("ID", "Risk", "Drug", "Predicted_IC50")
      p_drug <- ggpubr::ggboxplot(
        plot_long, x = "Drug", y = "Predicted_IC50", fill = "Risk",
        palette = CFG$RISK_COL, outlier.shape = NA, width = 0.8
      ) +
        ggpubr::stat_compare_means(aes(group = Risk), method = "wilcox.test", label = "p.signif") +
        ggplot2::theme_bw(base_size = 11) +
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
      save_gg_dual(p_drug, file.path(DIRS$drug, "drugSensitivity_boxplot"), width = 10, height = 5)
    }
  } else {
    msg("DrugPredictions.csv was not generated; skipping drug-sensitivity result export.")
  }
} else {
  msg("Skipping predicted drug-response analysis because oncoPredict and/or GDSC2 files were not available.")
}

# -----------------------------
# Final manifest
# -----------------------------
manifest <- data.frame(
  section = c(
    "functional_enrichment", "gsea", "immune_ssgsea", "tide", "immune_subtype", "checkpoint", "drug_sensitivity"
  ),
  status = c(
    file.exists(file.path(DIRS$functional, "GO_results.tsv")) | file.exists(file.path(DIRS$functional, "KEGG_results.tsv")),
    file.exists(file.path(DIRS$functional, "GSEA_results.tsv")),
    file.exists(file.path(DIRS$immune, "immune_ssgsea_scores.tsv")),
    file.exists(file.path(DIRS$immune, "TIDE_results.tsv")),
    file.exists(file.path(DIRS$immune, "immuneSubtype_results.tsv")),
    file.exists(file.path(DIRS$immune, "checkpoint_results.tsv")),
    file.exists(file.path(DIRS$drug, "drugSensitivity_results.tsv"))
  ),
  stringsAsFactors = FALSE
)
write.table(manifest, file = file.path(DIRS$logs, "run_manifest.tsv"),
            sep = "\t", quote = FALSE, row.names = FALSE)

msg("Finished 04_riskgroup_key_analyses.R")
